version: '3'
services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB={$POSTGRES_DB}
      - POSTGRES_USER={$POSTGRES_USER}
    ports:
      - 5432:5432
    volumes:
      - ./vocabularies:/vocabularies
      - ./data:/var/lib/postgresql/data